version: '3'

services:
  simple-journey:
    image: postgres:10
    environment:
      POSTGRES_USER: uaiso
      POSTGRES_DB: journey
      POSTGRES_PASSWORD: 123456
    command: ["-c", "shared_buffers=256MB", "-c", "max_connections=500"]
    ports:
      - 5432:5432

  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "16543:80"
    networks:
      - default
    depends_on:
      - simple-journey